# tombi: format.rules.table-keys-order = 'ascending'
[settings.shell.fish.abbrev]
'.' = 'source'
'?' = 'if'
al = 'la'
cmd = 'command'
export = 'set -x'
fn = 'function'
fns = 'functions'
fnsv = 'funcsave'
fun = 'function'
func = 'function'
h = 'help'
local = 'set -l'
loop = 'while true'
psrg = 'ps aux | rg'
which = 'whereis'
xopen = 'open'
