# tombi: format.rules.table-keys-order = "ascending"
[settings.shell.fish.subcommand_abbrevs]
apptainer.b = "build"
apptainer.sh = "shell"
apptainer.x = "exec"
atuin.a = "account"
atuin.dr = "doctor"
atuin.h = "history"
atuin.sc = "scripts"
atuin.se = "search"
brew.abv = "info"
brew.dr = "doctor"
brew.home = "homepage"
brew.instal = "install"
brew.lc = "livecheck"
brew.ln = "link"
brew.ls = "list"
brew.out = "outdated"
brew.pitdated = "outdated"
brew.post_install = "postinstall"
brew.remove = "uninstall"
brew.rm = "uninstall"
brew.tc = "typecheck"
brew.uninstal = "uninstall"
brew.uograde = "upgrade"
brew.up = "update"
brew.upg = "upgrade"
brew.yopgrade = "upgrade"
brew.ypgrade = "upgrade"
brz.a = "add"
brz.b = "branch"
brz.c = "commit"
brz.co = "checkout"
brz.d = "diff"
brz.st = "status"
bundle.a = "add"
bundle.b = "binstubs"
bundle.c = "check"
bundle.cfg = "config"
bundle.cn = "clean"
bundle.dr = "doctor"
bundle.e = "exec"
bundle.ex = "exec"
bundle.exe = "exec"
bundle.g = "gem"
bundle.h = "help"
bundle.i = "install"
bundle.ls = "list"
bundle.out = "outdated"
bundle.pack = "cache"
bundle.package = "cache"
bundle.s = "show"
bundle.u = "update"
bundle.up = "update"
bundle.x = "exec"
cargo.b = "build"
cargo.c = "check"
cargo.d = "doc"
cargo.r = "run"
cargo.rm = "remove"
cargo.t = "test"
chezmoi.a = "add"
chezmoi.ap = "apply"
chezmoi.dr = "doctor"
chezmoi.s = "status"
chezmoi.up = "update"
container.i = "image"
container.images = "image list"
container.ls = "list"
container.r = "registry"
container.rm = "delete"
container.s = "system"
dnf.check-update = "check-upgrade"
dnf.dg = "downgrade"
dnf.dsync = "distro-sync"
dnf.grp = "grp"
dnf.if = "info"
dnf.in = "install"
dnf.ls = "list"
dnf.mc = "makecache"
dnf.rei = "reinstall"
dnf.repoinfo = "repo info"
dnf.repolist = "repo list"
dnf.rm = "remove"
dnf.rq = "repoquery"
dnf.se = "search"
dnf.up = "upgrade"
dnf.update = "upgrade"
dnf.updateinfo = "advisory"
dnf.upgrade-minimal = "upgrade --minimal"
docker.bl = "build"
docker.ctx = "context"
docker.img = "image"
docker.net = "network"
docker.networks = "network ls"
docker.sys = "system"
docker.v = "volume"
docker.vls = "volume ls"
docker.vol = "volume"
docker.volumes = "volume ls"
docker.x = "exec"
dotnet.a = "add"
dotnet.b = "build"
dotnet.rm = "remove"
git.a = "add"
git.b = "branch"
git.c = "commit"
git.co = "checkout"
git.d = "diff"
git.st = "status"
gix.attrs = "attributes"
gix.r = "revision"
gix.remotes = "remote"
gix.rev = "revision"
go.b = "build"
jj.b = "bookmark"
jj.desc = "describe"
jj.evolution-log = "evolog"
jj.op = "operation"
jj.st = "status"
mise.a = "alias"
mise.b = "backends"
mise.cfg = "config"
mise.dr = "doctor"
mise.e = "env"
mise.exec = "x" # exec is the true command
mise.gen = "generate"
mise.i = "install"
mise.list = "ls"
mise.ln = "link"
mise.p = "plugins"
mise.r = "run"
mise.remove = "unuse"
mise.rm = "unuse"
mise.sh = "shell"
mise.t = "tasks"
mise.u = "use"
mise.up = "upgrade"
mise.v = "version"
mise.w = "watch"
nerdctl.bl = "build"
nerdctl.img = "image"
nerdctl.net = "network"
nerdctl.networks = "network ls"
nerdctl.sys = "system"
nerdctl.v = "volume"
nerdctl.vls = "volume ls"
nerdctl.vol = "volume"
nerdctl.volumes = "volume ls"
nerdctl.x = "exec"
npm.add = "install"
npm.add-user = "adduser"
npm.author = "owner"
npm.c = "config"
npm.cit = "install-ci-test"
npm.clean-install = "ci"
npm.clean-install-test = "install-ci-test"
npm.create = "init"
npm.ddp = "dedupe"
npm.dist-tags = "dist-tag"
npm.find = "search"
npm.hlep = "help"
npm.home = "docs"
npm.i = "install"
npm.ic = "ci"
npm.in = "install"
npm.info = "view"
npm.innit = "init"
npm.ins = "install"
npm.inst = "install"
npm.insta = "install"
npm.instal = "install"
npm.install-clean = "ci"
npm.isnt = "install"
npm.isnta = "install"
npm.isntal = "install"
npm.isntall = "install"
npm.isntall-clean = "ci"
npm.issues = "bugs"
npm.it = "install-test"
npm.la = "ll"
npm.list = "ls"
npm.ln = "link"
npm.ogr = "org"
npm.out = "outdated"
npm.r = "uninstall"
npm.rb = "rebuild"
npm.remove = "uninstall"
npm.rm = "uninstall"
npm.rum = "run"
npm.run-script = "run" # run-script is the true command but run is better
npm.s = "search"
npm.se = "search"
npm.show = "view"
npm.sit = "install-ci-test"
npm.t = "test"
npm.tst = "test"
npm.udpate = "update"
npm.un = "uninstall"
npm.unlink = "uninstall"
npm.up = "update"
npm.upgrade = "update"
npm.urn = "run"
npm.v = "view"
npm.verison = "version"
npm.why = "explain"
npm.x = "exec"
pnpm.dislink = "unlink"
pnpm.dr = "doctor"
pnpm.i = "install"
pnpm.it = "install-test"
pnpm.list = "ls"
pnpm.ln = "link"
pnpm.out = "outdated"
pnpm.rb = "rebuild"
pnpm.rm = "remove"
pnpm.run-script = "run"
pnpm.t = "test"
pnpm.tst = "test"
pnpm.un = "remove"
pnpm.uninstall = "remove"
pnpm.up = "update"
pnpm.upgrade = "update"
podlet.c = "compose"
podlet.g = "generate"
podlet.p = "podman"
podman.b = "build"
podman.bl = "build"
podman.context = "system connection"
podman.ctx = "system connection"
podman.gen = "generate"
podman.hc = "healthcheck"
podman.health = "healthcheck"
podman.img = "image"
podman.net = "network"
podman.networks = "network ls"
podman.sys = "system"
podman.v = "volume"
podman.vls = "volume ls"
podman.vol = "volume"
podman.volumes = "volume ls"
podman.x = "exec"
rustup.tc = "toolchain"
rustup.up = "update"
sq.dec = "decrypt"
sq.e = "encrypt"
sq.enc = "encrypt"
sq.s = "sign"
sq.v = "verify"
string.c = "collect"
string.e = "escape"
string.j = "join"
string.j0 = "join0"
string.le = "length"
string.len = "length"
string.lo = "lower"
string.m = "match"
string.p = "pad"
string.repl = "replace"
string.s = "split"
string.s0 = "split0"
string.sh = "shorten"
string.short = "shorten"
string.t = "trim"
string.tr = "trim"
string.une = "unescape"
string.up = "upper"
uv.a = "add"
uv.b = "build"
uv.pub = "publish"
uv.rm = "remove"
vivid.g = "generate"
vivid.p = "preview"
vivid.t = "themes"
zellij.a = "attach"
zellij.ac = "action"
zellij.d = "delete-session"
zellij.da = "delete-all-sessions"
zellij.e = "edit"
zellij.k = "kill-session"
zellij.ka = "kill-all-sessions"
zellij.la = "list-aliases"
zellij.ls = "list-sessions"
zellij.p = "plugin"
zellij.r = "run"
