[settings.npm.core]
sign-git-commit = true
sign-git-tag = true
init-author-email = "npm@brnr.link"
init-author-name = "Burner"

[settings.npm.by_os.darwin]
init-module = "${HOME}/.config/npm/config/npm-init.js"
cache = "${HOME}/Library/Caches/npm"

[settings.npm.by_os.linux]
init-module = "${XDG_CONFIG_HOME}/npm/config/npm-init.js"
cache = "${XDG_CACHE_HOME}/npm"
prefix = "${XDG_DATA_HOME}/npm"
logs-dir = "${XDG_STATE_HOME}/npm/logs"
