[settings.shell.pwsh.completers]
ast-grep = 'ast-grep completions powershell'
atuin = 'atuin gen-completions --shell powershell'
bcachefs = 'bcachefs completions powershell'
bws = 'bws completions powershell'
dotnet = 'dotnet completions script pwsh'
dprint = 'dprint completions powershell'
ein = 'ein completions --shell powershell'
erd = 'erd --completions powershell'
folderify = 'folderify --completions powershell'
genact = 'genact --print-completions powershell'
git-absorb = 'git-absorb --gen-completions powershell'
gix = 'gix completions --shell powershell'
hgrep = 'hgrep --generate-completion-script powershell'
komac = 'komac complete powershell'
kondo = 'kondo --completions powershell'
kwctl = 'kwctl completions --shell powershell'
ltrs = 'ltrs completions powershell'
miniserve = 'miniserve --print-completions powershell'
nickel = 'nickel gen-completions powershell'
onefetch = 'onefetch --generate powershell'
pdm = 'pdm completion powershell'
pixi = 'pixi completion --shell powershell'
proto = 'proto completions --shell powershell'
pueue = 'pueue completions power-shell'
py-spy = 'py-spy completions powershell'
railway = 'railway completion powershell'
rav1e = 'rav1e - -o - advanced --completion powershell'
rbw = 'rbw gen-completions powershell'
ruff = 'ruff generate-shell-completion powershell'
sentry-cli = 'sentry-cli completions powershell'
sg = 'sg completions powershell'
somo = 'somo generate-completions powershell'
spytrap-adb = 'spytrap-adb completions powershell'
tailscale = 'tailscale completion powershell'
tex-fmt = 'tex-fmt --completion powershell'
tombi = 'tombi completion powershell'
topgrade = 'topgrade --gen-completion powershell'
topiary = 'topiary completion powershell'
tree-sitter = 'tree-sitter complete --shell power-shell'
typeshare = 'typeshare completions powershell'
uv = 'uv generate-shell-completion powershell'
uvx = 'uvx --generate-shell-completion powershell'
vrc-get = 'vrc-get completion powershell'
'vrc-get.exe' = 'vrc-get.exe completion powershell'
warp-cli = 'warp-cli generate-completions powershell'
wasmtime = 'wasmtime completion powershell'
yr = 'yr completion powershell'
zellij = 'zellij setup --generate-completion powershell'
