# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ansible-playbook
description: Runs Ansible playbooks
parsing: disabled
completion:
  positionalany: ['$carapace.bridge.Argcomplete([ansible-playbook])']
