min_version = "2025.8.20"

[settings]
experimental = true
paranoid = false
not_found_auto_install = false
idiomatic_version_file_enable_tools = ["go", "java", "node", "python", "ruby"]
go_default_packages_file = "~/.config/mise/default-go-packages"
disable_tools = [
  "nim",
  "ollama",
  "rome",
  "solidity",
  "starknet-foundry",
  "starport",
  "wasmer",
  "youtube-dl",
  "aichat",
  "claude",
  "bun",
  "claude-squad",
  "codex",
  "specstory",
  "code",
  "codebuff",
  "amp",
  "gemini-cli",
  "jules",
]
disable_hints = [
  "python_precompiled",
  "registry",
  "outdated_bump",
  "python_multi",
]
disable_backends = [
  "gem", # security
]
env_cache = true

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[settings.python]
default_packages_file = "~/.config/mise/default-python-packages"
uv_venv_auto = true

[settings.npm]
package_manager = "pnpm"

[tools]
cargo-binstall = "latest"
"github:VorpalBlade/chezmoi_modify_manager" = "latest"
