[settings.homebrew.forbiddden]
cask = [
  '5ire', # ai
  'ace-studio', # ai
  'agent-tars', # ai 
  'agentkube', # ai
  'aide-app', # ai
  'aifun', # ai
  'aigcpanel', # ai
  'aionui', # ai
  'ajour', # activision-blizzard
  'amazon-q', # ai AND absurdly questionably behavior
  'anchor-wallet', # cryptocurrency
  'anythingllm', # ai
  'ark-desktop-wallet', # cryptocurrency
  'armory', # cryptocurrency
  'atomic-wallet', # cryptocurrency
  'augur', # cryptocurrency
  'ayugram', # telegram
  'backyard-ai', # ai
  'baritone', # spotify
  'battle-net', # activison-blizzard
  'binance', # cryptocurrency
  'bison-wallet', # cryptocurrency
  'bisq', # cryptocurrency
  'bitbox', # cryptocurrency
  'bitcoin-core', # cryptocurrency
  'block-goose', # ai
  'blockstack', # cryptocurrency
  'blockstream', # cryptocurrency
  'blockstream-green', # cryptocurrency
  'bloop', # ai
  'bluewallet', # cryptocurrency
  'boltai', # ai
  'boss', # ai
  'brave-browser', # homophobia
  'brave-browser@beta', # homophobia
  'brave-browser@dev', # homophobia
  'brave-browser@nightly', # homophobia
  'browseros', # ai
  'btcpayserver-vault', # cryptocurrency
  'caprine', # facebook
  'chatall', # ai
  'chatbox', # ai
  'chatgpt', # ai
  'chatgpt-atlas', # ai
  'chatwise', # ai
  'cherry-studio', # ai
  'chia', # cryptocurrency
  'cityofzion-neon', # cryptocurrency
  'claude', # ai
  'claude-code', # ai
  'cmd', # ai
  'codebolt', # ai
  'coderabbit', # ai
  'codex', # ai
  'coin-wallet', # cryptocurrency
  'coinomi-wallet', # cryptocurrency
  'comfyui', # ai
  'conductor', # ai
  'context', # ai
  'copilot-for-xcode', # ai
  'cursor', # ai
  'cursor-cli', # ai
  'daedalus-mainnet', # cryptocurrency
  'dash-dash', # cryptocurrency
  'dayflow', # ai
  'decentr', # cryptocurrency
  'decrediton', # cryptocurrency
  'deepchat', # ai
  'deepl', # ai
  'diffusionbee', # ai
  'dogecoin', # cryptocurrency
  'doubao', # ai
  'draw-things', # ai
  'droid', # ai
  'dyad', # ai
  'electron-cash', # cryptocurrency
  'electronmail', # protonmail
  'electrum', # cryptocurrency
  'electrum-grs', # cryptocurrency
  'electrum-ltc', # cryptocurrency
  'electrumsv', # cryptocurrency
  'elephas', # ai
  'elephas@beta', # ai
  'emdash', # ai
  'ethereum-wallet', # cryptocurrency
  'feather', # cryptocurrency
  'fig', # see amazon-q
  'filo', # ai
  'firefly', # cryptocurrency
  'firefly-iota-desktop', # cryptocurrency
  'firefly-shimmer', # cryptocurrency
  'fixkey', # ai
  'flowdown', # ai
  'forkgram-telegram', # telegram
  'ganache', # cryptocurrency
  'geekbench-ai', # ai
  'github',
  'github-copilot-for-xcode', # ai
  'github@beta',
  'goofy', # facebook
  'google-assistant',
  'google-chrome',
  'google-chrome@beta',
  'google-chrome@canary',
  'google-chrome@dev',
  'gpt4all', # ai
  'granola', # ai
  'greenery', # cryptocurrency
  'grids', # facebook
  'groestlcoin-core', # cryptocurrency
  'grs-bluewallet', # cryptocurrency
  'guilded', # roblox
  'hacker-menu', # orange site
  'hedy', # ai
  'highlight', # ai
  'highlight-ai', # ai
  'hotovo-aider-desk', # ai
  'hstracker', # activision-blizzard
  'huggingchat', # ai
  'igdm', # facebook
  'impel', # ai
  'infoflow', # ai
  'itermai', # ai
  'jamie', # ai
  'jan', # ai
  'katrain', # ai
  'kimi', # ai
  'kiro', # ai
  'kyokan-bob', # cryptocurrency
  'langflow', # ai
  'league-of-legends', # your honor, league of legends
  'ledger-live', # cryptocurrency
  'ledger-wallet', # cryptocurrency
  'limitless', # ai
  'litecoin', # cryptocurrency
  'llamabarn', # ai
  'llamachat', # ai
  'lm-studio', # ai
  'lobehub', # ai
  'macai', # ai
  'mailbutler', # ai
  'mem', # ai
  'memory', # ai
  'messenger', # facebook
  'messenger-native', # facebook
  'meta-quest-developer-hub', # facebook
  'microsoft-edge',
  'microsoft-edge@beta',
  'microsoft-edge@canary',
  'microsoft-edge@dev',
  'mindmac', # ai
  'mixin', # cryptocurrency
  'mochi-diffusion', # ai
  'monero-wallet', # cryptocurrency
  'msty', # ai
  'mumu-x', # ai
  'mycrypto', # cryptocurrency
  'mymonero', # cryptocurrency
  'nano', # cryptocurrency
  'nano-node', # cryptocurrency
  'nao', # ai
  'nasas-eyes', # US
  'nault', # cryptocurrency
  'netron', # ai
  'nocturn', # twitter
  'notesollama', # ai
  'ollama', # ai
  'ollama-app', # ai
  'ollamac', # ai
  'onekey', # cryptocurrency
  'onlook', # ai
  'opcode', # ai
  'opencat', # ai
  'opera', # loan-shark
  'opera-air', # loan-shark
  'opera-crypto@developer', # loan-shark
  'opera-gx', # loan-shark
  'opera-mobile-emulator', # loan-shark
  'opera-neon', # loan-shark
  'opera@beta', # loan-shark
  'opera@developer', # loan-shark
  'operadriver', # loan-shark
  'origin', # fascism
  'orion', # i don't like kagi
  'osaurus', # ai
  'pally', # ai
  'pdf-pals', # ai
  'pdl', # ai
  'planet', # cryptocurrency
  'poe', # ai
  'proton-drive', # fascism
  'proton-mail', # fascism
  'proton-mail-bridge', # fascism
  'proton-pass', # fascism
  'protonmail-import-export', # fascism
  'protonvpn', # fascism
  'psst', # spotify
  'raiderio', # activision-blizzard
  'ramme', # facebook
  'rapidminer-studio', # ai
  'raycast', # ai
  'remix-ide', # cryptocurrency
  'repo-prompt', # ai
  'rewind', # ai
  'rewritebar', # ai
  'rivet', # ai
  'rize', # ai
  'roblox', # roblox
  'robloxstudio', # roblox
  'runway', # ai
  'sanctum', # ai
  'scatter', # cryptocurrency
  'shortwave', # ai
  'spark-ar-studio', # facebook
  'sparkplate', # cryptocurrency
  'sparrow', # cryptocurrency
  'specter', # cryptocurrency
  'spotify', # spotify
  'spotify4bigsur', # spotify
  'spotspot', # spotify
  'stability-matrix', # ai
  'starcraft', # activision-blizzard
  'status', # cryptocurrency
  'statusfy', # spotify
  'stravu-crystal', # ai
  'superhuman', # ai
  'superwhisper', # ai
  'swama', # ai
  'telegram', # telegram
  'telegram-a', # telegram
  'telegram-desktop', # telegram
  'telegram-desktop@beta', # telegram
  'thebrowsercompany-dia', # ai
  'threema', # threema
  'threema-work', # threema
  'threema@beta', # threema
  'tint', # fascism
  'trae', # ai
  'trae-cn', # ai
  'trezor-bridge', # cryptocurrency
  'trezor-suite', # cryptocurrency
  'trinity', # cryptocurrency
  'turbotax-2024',
  'typefully', # twitter
  'ui-tars', # ai
  'upm', # deprecated
  'vertcoin-core', # cryptocurrency
  'vibemeter', # ai
  'vibetunnel', # ai
  'vincelwt-chatgpt', # ai
  'voicenotes', # ai
  'void', # ai
  'vpn-by-google-one',
  'vu', # facebook
  'warcraft-logs-uploader', # activision-blizzard
  'wasabi-wallet', # cryptocurrency
  'whodb', # ai
  'windsurf', # ai
  'windsurf@next', # ai
  'witsy', # ai
  'workplace-chat', # facebook
  'wowmatrix', # activision-blizzard
  'wowup', # activision-blizzard
  'yuanbao', # ai
  'zecwallet-lite', # cryptocurrency
  'zeronet', # cryptocurrency
  'zoo-design-studio', # ai
]

formula = [
  'aiac', # ai
  'aichat', # ai
  'aicommit', # ai
  'aicommit2', # ai
  'aicommits', # ai
  'aider', # ai
  'aiken', # cryptocurrency
  'airtable-mcp-server', # ai
  'aiven-client', # ai
  'alejandra', # nix
  'aptos', # cryptocurrency
  'arcade-learning-environment', # ai
  'arturo', # fascism
  'ata', # ai
  'backgroundremover', # ai
  'bcoin', # cryptocurrency
  'bitcoin', # cryptocurrency
  'block-goose-cli', # ai
  'cadence', # cryptocurrency
  'cagent', # ai
  'cai', # ai
  'caracal', # cryptocurrency
  'ccusage', # ai
  'chainhook', # cryptocurrency
  'chatblade', # ai
  'chawan', # nim
  'chrome-devtools-mcp', # ai
  'circumflex', # orange site
  'clarinet', # cryptocurrency
  'claude-cmd', # ai
  'claude-code-router', # ai
  'claude-hooks', # ai
  'claude-squad', # ai
  'claudekit', # ai
  'cliproxyapi', # ai
  'cobo-cli', # ai
  'code2prompt', # ai
  'codex', # ai
  'cog', # ai
  'cointop', # cryptocurrency
  'context7-mcp', # ai
  'core-lightning', # cryptocurrency
  'cortexso', # ai
  'cql', # cryptocurrency
  'crytic-compile', # cryptocurrency, leaf dependency
  'daemontools', # cryptocurrency
  'dstack', # ai
  'echidna', # cryptocurrency
  'envd', # ai
  'erigon', # cryptocurrency
  'ethereum', # cryptocurrency
  'fabric-ai', # ai
  'fades', # use `uv run`
  'fastmcp', # ai
  'firefly', # cryptocurrency
  'flow-cli', # cryptocurrency
  'foundry', # cryptocurrency
  'framework-tool-tui', # framework
  'gbox', # ai
  'gemini-cli', # ai
  'genai-toolbox', # ai
  'gitea-mcp-server', # ai
  'github-mcp-server', # ai
  'gitingest', # ai
  'gollama', # ai
  'gorilla-cli', # ai
  'gptline', # ai
  'gptme', # ai
  'gptscript', # ai
  'grin', # cryptocurrency
  'grin-wallet', # cryptocurrency
  'groestlcoin', # cryptocurrency
  'hf-mcp-server', # ai
  'huggingface-cli', # ai
  'hyper-mcp', # ai
  'ignite', # cryptocurrency
  'ioctl', # cryptocurrency
  'ipget', # cryptocurrency
  'k8sgpt', # ai
  'kagent', # ai
  'kimi-cli', # ai
  'kubectl-ai', # ai
  'kubernetes-mcp-server', # ai
  'kuzco', # ai
  'lexido', # ai
  'libbitcoin-blockchain', # cryptocurrency
  'libbitcoin-client', # cryptocurrency
  'libbitcoin-consensus', # cryptocurrency, leaf dependency
  'libbitcoin-database', # cryptocurrency
  'libbitcoin-explorer', # cryptocurrency
  'libbitcoin-network', # cryptocurrency
  'libbitcoin-node', # cryptocurrency
  'libbitcoin-protocol', # cryptocurrency
  'libbitcoin-server', # cryptocurrency
  'libbitcoin-system', # cryptocurrency, leaf dependency
  'librespot', # spotify
  'lighthouse', # cryptocurrency
  'litecli', # ai
  'llama.cpp', # ai
  'llm', # ai
  'localai', # ai
  'mallet', # ai
  'mcp-atlassian', # ai
  'mcp-get', # ai
  'mcp-google-sheets', # ai
  'mcp-grafana', # ai
  'mcp-inspector', # ai
  'mcp-proxy', # ai
  'mcp-publisher', # ai
  'mcp-server-chart', # ai
  'mcp-server-kubernetes', # ai
  'mcp-toolbox', # ai
  'mcphost', # ai
  'mcpm', # ai
  'mcptools', # ai
  'medusa', # cryptocurrency
  'mentat', # ai
  'mikutter', # twitter
  'min-lang', # fascism
  'mlx-lm', # ai
  'mods', # ai
  'monero', # cryptocurrency
  'n8n-mcp', # ai
  'nanobot', # ai
  'ncspot', # spotify
  'nim', # homophobia
  'nixfmt', # nix
  'nixpacks', # nix
  'notion-mcp-server', # ai
  'oasis', # cryptocurrency
  'ollama', # ai
  'omnara', # ai
  'onnx', # ai
  'opencode', # ai
  'openssl@1.1', # security, deprecated
  'openvino', # ai
  'ord', # cryptocurrency
  'oterm', # ai
  'oxen', # ai
  'playwright-mcp', #ai
  'plz-cli', # ai
  'promptfoo', # ai
  'qwen-code', # ai
  'rails-mcp-server', # ai
  'ramalama', # ai
  'rawdog', # ai
  'repomix', # ai
  'roblox-ts', # roblox
  'rojo', # roblox
  'rulesync', # ai
  'rustywind', # fascism
  'salesforce-mcp', # ai
  'screenpipe', # ai
  'shimmy', # ai
  'shortest', # ai
  'shpotify', # spotify
  'slack-mcp-server', # ai
  'slither-analyzer', # cryptocurrency, leaf dependency
  'solana', # cryptocurrency
  'solc-select', # cryptocurrency
  'solhint', # cryptocurrency
  'solidity', # cryptocurrency
  'spicetify-cli', # spotify
  'spotify_player', # spotify
  'spotifyd', # spotify
  'statix', # nix
  'stellar-cli', # cryptocurrency
  'stellar-core', # cryptocurrency
  'sui', # cryptocurrency
  'supabase-mcp-server', # ai
  'sysaidmin', # ai
  't-completion', # twitter
  'tailwindcss', # fascism
  'tailwindcss-language-server', # fascism
  'taskopen', # fascism
  'tdd-guard', # ai
  'tdlib', # telegram
  'teku', # cryptocurrency
  'telegram-downloader', # telegram
  'tendermint', # cryptocurrency
  'tenere', # ai
  'terraform-mcp-server', # ai
  'teslamate', # fascism
  'tfmcp', # ai
  'tgpt', # ai
  'tmuxai', # ai
  'trezor-agent', # cryptocurrency
  'trezor-bridge', # cryptocurrency
  'truffle', # cryptocurrency
  'tsui', # fascism
  'tuisky', # bluesky
  'tweakcc', # ai
  'twty', # twitter
  'unitycatalog', # ai
  'vespa-cli', # ai
  'vibecheck', # ai
  'vtcode', # ai
  'wagyu', # cryptocurrency
  'wally', # roblox
  'wasmer', # preference
  'wassette', # ai
  'wownero', # cryptocurrency
  'xgboost', # ai
  'xgo', # ai
  'xlearn', # ai
  'xmrig', # cryptocurrency
  'yek', # ai
  'yutu', # ai
]

# These are mostly forbidden to prevent unexpected from-source builds.
# If it needs to be built from source, do that another way.
# If it's python, use `uv tool`
linux = [
  'cmake',
  'dbus',
  'dotnet',
  'fish',
  'git-open', # Broken on Linux
  'glib',
  'go',
  'ncurses',
  'node',
  'openssl@3', # Broken with my setup
  'perl',
  'pkg-config', # Bottle not relocatable
  'ruby',
  'systemd',
]

tap = [
  'AdoptOpenJDK/openjdk', # deprecated
  'aquaproj/aqua', # aqua is in homebrew/core
  'ethereum/ethereum',
  'homebrew/aliases', # deprecated
  'homebrew/bundle', # deprecated
  'homebrew/cask-drivers', # deprecated
  'homebrew/cask-fonts', # deprecated
  'homebrew/cask-versions', # deprecated
  'homebrew/formula-analytics', # deprecated
  'homebrew/services', # deprecated
  'nanovms/ops', # builds from source with a weird script
  'neovim/neovim', # deprecated
  'oven-sh/bun', # fascism
  'pkgxdev/made', # cryptocurrency-adjacent
  'render-oss/render', # Mac OS only
  'teamookla/speedtest', # Mac OS only
  'v2ray/v2ray', # deprecated
]
