# tombi: format.rules.table-keys-order = 'ascending'
[extensions]
3fr = 'Preview'
af = 'Affinity'
afassets = 'Affinity'
afbook = 'Affinity Publisher 2'
afbrushes = 'Affinity'
afdesign = 'Affinity'
'afdesign~backup~' = 'Affinity'
'afdesign~lock~' = 'Affinity'
'afdesign~tmp~' = 'Affinity'
affinity = 'Affinity'
affinity_designer = 'Affinity'
affinity_photo = 'Affinity'
'affinity~backup~' = 'Affinity'
'affinity~lock~' = 'Affinity'
'affinity~tmp~' = 'Affinity'
afluts = 'Affinity'
afmacros = 'Affinity'
afpackage = 'Affinity'
afphoto = 'Affinity'
'afphoto~backup~' = 'Affinity'
'afphoto~lock~' = 'Affinity'
'afphoto~tmp~' = 'Affinity'
afpub = 'Affinity'
'afpub~backup~' = 'Affinity'
'afpub~lock~' = 'Affinity'
'afpub~tmp~' = 'Affinity'
afstudio = 'Affinity'
aftemplate = 'Affinity'
'af~backup~' = 'Affinity'
'af~lock~' = 'Affinity'
'af~tmp~' = 'Affinity'
ai = 'Preview'
aif = 'VLC'
aifc = 'VLC'
aiff = 'VLC'
arw = 'Preview'
asax = 'Rider'
ascx = 'Rider'
ashx = 'Rider'
asmdef = 'Rider'
asmref = 'Rider'
asmx = 'Rider'
aspx = 'Rider'
astro = 'WebStorm'
avif = 'Preview'
axd = 'Rider'
bash_aliases = 'Visual Studio Code'
bash_completions = 'Visual Studio Code'
bash_functions = 'Visual Studio Code'
bash_login = 'Visual Studio Code'
bash_logout = 'Visual Studio Code'
bash_profile = 'Visual Studio Code'
bash_variables = 'Visual Studio Code'
bashrc = 'Visual Studio Code'
bettertouchtool = 'BetterTouchTool'
blend = 'Blender'
bmp = 'Preview'
brewfile = 'Visual Studio Code'
bttactionplugin = 'BetterTouchTool'
bttcompressedpresetbundle = 'BetterTouchTool'
bttfloatingmenuitems = 'BetterTouchTool'
bttfloatingmenus = 'BetterTouchTool'
bttkeyboardshortcuts = 'BetterTouchTool'
bttkeysequences = 'BetterTouchTool'
bttlicense = 'BetterTouchTool'
bttmagicmouse = 'BetterTouchTool'
bttmouse = 'BetterTouchTool'
bttothertriggers = 'BetterTouchTool'
bttplugin = 'BetterTouchTool'
bttpreset = 'BetterTouchTool'
bttpresetbundle = 'BetterTouchTool'
bttpresetcompressed = 'BetterTouchTool'
bttpresetzip = 'BetterTouchTool'
bttsdplugin = 'BetterTouchTool'
bttstreamdeckplugin = 'BetterTouchTool'
btttbplugin = 'BetterTouchTool'
btttouchbarplugin = 'BetterTouchTool'
btttrackpad = 'BetterTouchTool'
c = 'CLion'
'c++' = 'CLion'
cc = 'CLion'
cdda = 'VLC'
cg = 'Rider'
cginc = 'Rider'
cjs = 'WebStorm'
cjsx = 'WebStorm'
cmake = 'CLion'
code-snippets = 'Visual Studio Code'
code-workspace = 'Visual Studio Code'
coffee = 'WebStorm'
compute = 'Rider'
containerfile = 'Visual Studio Code'
cpp = 'CLion'
cr2 = 'Preview'
cr3 = 'Preview'
crw = 'Preview'
cs = 'Rider'
cshtml = 'Rider'
csproj = 'Rider'
cxx = 'CLion'
dcr = 'Preview'
dmw = 'dotMemory'
dng = 'Preview'
dockerfile = 'Visual Studio Code'
doxygen = 'CLion'
dtp = 'dotTrace'
dtt = 'dotTrace'
eleventyignore = 'WebStorm'
elv = 'Visual Studio Code'
elvts = 'Visual Studio Code'
eps = 'Affinity'
erf = 'Preview'
es6 = 'WebStorm'
eslintignore = 'WebStorm'
eslintrc = 'WebStorm'
exr = 'Preview'
eyaml = 'Visual Studio Code'
eyml = 'Visual Studio Code'
fff = 'Preview'
fish = 'Visual Studio Code'
flac = 'VLC'
fsi = 'Rider'
fsproj = 'Rider'
fsscript = 'Rider'
fsx = 'Rider'
gant = 'IntelliJ IDEA'
gif = 'Preview'
gitattributes = 'Visual Studio Code'
gitconfig = 'Visual Studio Code'
gitignore = 'Visual Studio Code'
go = 'GoLand'
go2 = 'GoLand'
gohtml = 'GoLand'
gradle = 'IntelliJ IDEA'
groovy = 'IntelliJ IDEA'
h = 'CLion'
'h++' = 'CLion'
hdp = 'Affinity'
hdr = 'Preview'
heic = 'Preview'
heif = 'Preview'
hh = 'CLion'
hlsli = 'Rider'
hphp = 'PhpStorm'
hpp = 'CLion'
hprof = 'IntelliJ IDEA'
html = 'Firefox'
hxx = 'CLion'
icns = 'Preview'
ico = 'Preview'
iiq = 'Preview'
ipr = 'IntelliJ IDEA'
j2 = 'PyCharm'
j2k = 'Preview'
jade = 'WebStorm'
jav = 'IntelliJ IDEA'
java = 'IntelliJ IDEA'
jinja = 'PyCharm'
jinja2 = 'PyCharm'
jp2 = 'Preview'
jpeg = 'Preview'
jpegxr = 'Affinity'
jpg = 'Preview'
jshintignore = 'WebStorm'
jshintrc = 'WebStorm'
json = 'Visual Studio Code'
jsonc = 'Visual Studio Code'
jsx = 'WebStorm'
jxl = 'Preview'
jxr = 'Affinity'
kt = 'IntelliJ IDEA'
kts = 'IntelliJ IDEA'
litcoffee = 'WebStorm'
lua = 'Visual Studio Code'
m = 'Xcode'
m2a = 'VLC'
m3u = 'VLC'
m4a = 'VLC'
m4v = 'IINA'
master = 'Rider'
mdx = 'WebStorm'
meson = 'CLion'
mkv = 'IINA'
mm = 'Xcode'
mos = 'Preview'
mov = 'IINA'
mp2 = 'VLC'
mp3 = 'VLC'
mpeg = 'IINA'
mrw = 'Preview'
nef = 'Preview'
nettrace = 'dotTrace'
nodemonignore = 'WebStorm'
npmignore = 'WebStorm'
nrw = 'Preview'
nu = 'Visual Studio Code'
nuxtignore = 'WebStorm'
oga = 'VLC'
ogg = 'VLC'
ogv = 'IINA'
opus = 'VLC'
orf = 'Preview'
org = 'Visual Studio Code'
overridetasks = 'Rider'
pbxproj = 'Xcode'
pdf = 'Preview'
pef = 'Preview'
pgm = 'Preview'
php = 'PhpStorm'
php3 = 'PhpStorm'
php4 = 'PhpStorm'
php5 = 'PhpStorm'
php7 = 'PhpStorm'
phpt = 'PhpStorm'
phtml = 'PhpStorm'
pls = 'VLC'
png = 'Preview'
props = 'Rider'
ps1 = 'Visual Studio Code'
psb = 'Affinity'
psd = 'Preview'
psd1 = 'Visual Studio Code'
psm1 = 'Visual Studio Code'
pug = 'WebStorm'
pxd = 'PyCharm'
pxi = 'PyCharm'
py = 'PyCharm'
py3 = 'PyCharm'
pyi = 'PyCharm'
pyw = 'PyCharm'
pyx = 'PyCharm'
raf = 'Preview'
raw = 'Preview'
razor = 'Rider'
rdf = 'Firefox'
rs = 'RustRover'
rst = 'Visual Studio Code'
rw2 = 'Preview'
rwl = 'Preview'
sass = 'WebStorm'
scss = 'WebStorm'
sln = 'Rider'
slnf = 'Rider'
slnx = 'Rider'
sr2 = 'Preview'
srf = 'Preview'
srw = 'Preview'
sublime-syntax = 'Sublime Text'
svelte = 'WebStorm'
svg = 'Affinity'
swift = 'Xcode'
tasks = 'Rider'
tga = 'Preview'
tif = 'Preview'
tiff = 'Preview'
tmlanguage = 'Sublime Text'
tmtheme = 'Sublime Text'
toml = 'Visual Studio Code'
usd = 'Preview'
usda = 'Preview'
usdz = 'Preview'
uss = 'Rider'
uxml = 'Rider'
vb = 'Rider'
vbproj = 'Rider'
vue = 'WebStorm'
wav = 'VLC'
wdp = 'Affinity'
webm = 'IINA'
webp = 'Preview'
xaml = 'Rider'
xcodeproj = 'Xcode'
xcworkspace = 'Xcode'
xht = 'Firefox'
xhtml = 'Firefox'
xul = 'Firefox'
yaml = 'Visual Studio Code'
yarnignore = 'WebStorm'
yml = 'Visual Studio Code'
zlogin = 'Visual Studio Code'
zlogout = 'Visual Studio Code'
zprofile = 'Visual Studio Code'
zshenv = 'Visual Studio Code'
zshrc = 'Visual Studio Code'

# tombi: format.rules.table-keys-order = 'ascending'
[schemes]
affinity = 'Affinity'
affinity-designer = 'Affinity Designer 2'
affinity-designer2-dropbox-auth = 'Affinity Designer 2'
affinity-photo = 'Affinity Photo 2'
affinity-photo2-dropbox-auth = 'Affinity Photo 2'
affinity-publisher = 'Affinity Publisher 2'
affinity-publisher2-dropbox-auth = 'Affinity Publisher 2'
btt = 'BetterTouchTool'
bttfeedback = 'BetterTouchTool'
github-mac = 'Tower'
gittower = 'Tower'
goland = 'GoLand'
http = 'Firefox'
https = 'Firefox'
ical = 'Calendar'
idea = 'IntelliJ IDEA'
iina = 'IINA'
karabiner = 'Karabiner-Elements'
kitty = 'kitty'
mailto = 'Mail'
markedit = 'MarkEdit'
obsidian = 'Obsidian'
odt = 'LibreOffice'
onepassword = '1Password'
onepassword8 = '1Password'
phpstorm = 'PhpStorm'
podman-desktop = 'Podman Desktop'
pycharm = 'PyCharm'
rtf = 'LibreOffice'
rustrover = 'RustRover'
sgnl = 'Signal'
signalcaptcha = 'Signal'
slack = 'Slack'
sourcetree = 'Tower'
ticktick = 'TickTick'
trello = 'Trello'
txt = 'CotEditor'
vscode = 'Visual Studio Code'
vscodium = 'VSCodium'
weather = 'Weather'
webcal = 'Calendar'
webstorm = 'WebStorm'
x-github-client = 'Tower'
zoommtg = 'zoom.us'
zoomus = 'zoom.us'

# tombi: format.rules.table-keys-order = 'ascending'
[types]
aiff = 'VLC'
avi = 'IINA'
bmp = 'Preview'
c-source = 'CLion'
'com.apple.default-app.mail-client' = 'Mail'
'com.apple.default-app.web-browser' = 'Firefox'
'com.apple.m4a-audio' = 'VLC'
'com.apple.m4v-video' = 'IINA'
gif = 'Preview'
heic = 'Preview'
heif = 'Preview'
jpeg = 'Preview'
mp3 = 'VLC'
mpeg = 'IINA'
mpeg2-video = 'IINA'
mpeg4-movie = 'IINA'
'org.xiph.flac' = 'VLC'
plain-text = 'CotEditor'
png = 'Preview'
python-script = 'PyCharm'
quicktime-movie = 'IINA'
raw-image = 'Preview'
rtf = 'LibreOffice'
svg = 'Affinity Designer 2'
swift-source = 'Xcode'
text = 'CotEditor'
tiff = 'Preview'
wav = 'VLC'
webp = 'Preview'
