[settings.shell.zsh.compsys]
# This *should* be a list, but it works fine if there are spaces in it,
# so multiple commands can be defined on each line.
# I'm not doing that though, since the code gets messier
carapace = [
  "acat",
  "acpi",
  "acpid",
  "act",
  "adb",
  "adiff",
  "age",
  "age-keygen",
  "agg",
  "als",
  "alsamixer",
  "ansible",
  "ansible-config",
  "ansible-console",
  "ansible-doc",
  "ansible-galaxy",
  "ansible-inventory",
  "ansible-playbook",
  "ansible-pull",
  "ansible-test",
  "ansible-vault",
  "ant",
  "antidot",
  "apack",
  "apk",
  "apko",
  "aplay",
  "apptainer",
  "apptainer.lima",
  "appy",
  "apropos",
  "apt-cache",
  "apt-get",
  "ar",
  "archlinux-java",
  "arduino-cli",
  "arecord",
  "arepack",
  "argo",
  "argocd",
  "argocd-vault-plugin",
  "aria2c",
  "artisan",
  "as-tree",
  "asciinema",
  "asdf",
  "atmos",
  "atool",
  "aunpack",
  "autoconf",
  "avdmanager",
  "awk",
  "aws",
  "aws-nuke",
  "az",
  "b2sum",
  "b3sum",
  "baobab",
  "basename",
  "bash",
  "bash-language-server",
  "bat",
  "batdiff",
  "batgrep",
  "batman",
  "bats",
  "bc",
  "bd_info",
  "bd_list_titles",
  "bd_splice",
  "benthos",
  "bingrep",
  "bkt",
  "black",
  "bloop",
  "bluetoothctl",
  "boundary",
  "bpython",
  "brotli",
  "bru",
  "btop",
  "buf",
  "buildah",
  "buildctl",
  "but",
  "bzdiff",
  "caddy",
  "cal",
  "calibre",
  "capslock",
  "carapace",
  "carapace-bridge",
  "carapace-parse",
  "carapace-spec",
  "carapace-spec-man",
  "carapace.exe",
  "cargo",
  "cat",
  "cdebug",
  "cdk",
  "cdk8s",
  "cekit",
  "cfdisk",
  "chamber",
  "changie",
  "charm",
  "chcpu",
  "chdman",
  "cheese",
  "chezmoi.exe",
  "chgrp",
  "chmod",
  "chown",
  "chpasswd",
  "chroma",
  "chromium",
  "chroot",
  "chsh",
  "circleci",
  "cksum",
  "clair",
  "clamav-config",
  "clamav-milter",
  "clambc",
  "clamconf",
  "clamd",
  "clamdscan",
  "clamdtop",
  "clamonacc",
  "clamscan",
  "clamsubmit",
  "clusterctl",
  "cmus",
  "code",
  "code-insiders",
  "codecov",
  "colima",
  "comm",
  "commitlint",
  "conc",
  "concurrently",
  "conda",
  "conda-content-trust",
  "conda-env",
  "conky",
  "consul",
  "cookiecutter",
  "copa",
  "coredumpctl",
  "cosign",
  "cp",
  "cpu_profiler.d",
  "crane",
  "crc",
  "csplit",
  "csview",
  "ctlptl",
  "cue",
  "cura",
  "curl",
  "cut",
  "d2",
  "dagger",
  "dark-mode",
  "darktable",
  "darktable-cli",
  "dart",
  "dasel",
  "dashing",
  "date",
  "dav1d",
  "dblab",
  "dbt",
  "dc",
  "dd",
  "deadcode",
  "delta",
  "deno",
  "desktop-file-install",
  "devbox",
  "devcontainer",
  "devpod",
  "devspace",
  "df",
  "dfc",
  "dict",
  "diff",
  "diff3",
  "diffoci",
  "difft",
  "dig",
  "dir",
  "dircolors",
  "direnv",
  "dirname",
  "diskus",
  "dive",
  "dlv",
  "dmenu",
  "dmesg",
  "dms",
  "dnf",
  "dngconverter",
  "dnscontrol",
  "dnsmasq",
  "doas",
  "docker",
  "docker-buildx",
  "docker-compose",
  "docker-scan",
  "docker.lima",
  "dockerd",
  "dockerfmt",
  "doctl",
  "docuum",
  "doing",
  "dos2unix",
  "dotenv-linter",
  "downgrade",
  "dpkg",
  "draft",
  "driftctl",
  "du",
  "dua",
  "duf",
  "dum",
  "dura",
  "ebook-convert",
  "eget",
  "egrep",
  "electron",
  "elvish",
  "ente",
  "env",
  "envsubst",
  "exa",
  "exercism",
  "exercism.exe",
  "expand",
  "expr",
  "extcheck",
  "eza",
  "f2",
  "faas",
  "faas-cli",
  "factor",
  "fakechroot",
  "fakeroot",
  "fastfetch",
  "fc-cache",
  "fc-cat",
  "fc-conflist",
  "fc-list",
  "fd",
  "fdisk",
  "feishu2md",
  "ffmate",
  "ffmpeg",
  "fgrep",
  "file",
  "fileicon",
  "find",
  "findmnt",
  "firefox",
  "fish",
  "fish_key_reader",
  "flatpak",
  "flowpipe",
  "flutter",
  "fly",
  "flyctl",
  "fmt",
  "fnm",
  "fold",
  "foot",
  "freeze",
  "ftp",
  "ftpd",
  "fury",
  "fx",
  "fzf",
  "gamemoderun",
  "gator",
  "gatsby",
  "gci",
  "gcloud",
  "gdb",
  "gdown",
  "gdu",
  "get-env",
  "getsebool",
  "gftp",
  "ggshield",
  "gh",
  "gh-dash",
  "ghorg",
  "ghostty",
  "ghostunnel",
  "gibo",
  "gimp",
  "git",
  "git-authors",
  "git-unlock",
  "git-utimes",
  "gitk",
  "gitlab-runner",
  "gitleaks",
  "gitlint",
  "gitsign",
  "gittower",
  "gitui",
  "gk",
  "glab",
  "glib-compile-schemas",
  "glow",
  "glow.exe",
  "gnome-keyring",
  "gnome-keyring-daemon",
  "gnome-maps",
  "gnome-terminal",
  "go",
  "go-carpet",
  "gocyclo",
  "gofmt",
  "goimports",
  "golangci-lint",
  "gomplate",
  "gonew",
  "google-chrome",
  "gopass",
  "gopls",
  "goreleaser",
  "goweight",
  "gparted",
  "gpasswd",
  "gpg",
  "gpg-agent",
  "gping",
  "gradle",
  "graphql",
  "greenmask",
  "grep",
  "grex",
  "gron",
  "groupadd",
  "groupdel",
  "groupmems",
  "groupmod",
  "groups",
  "grype",
  "gsa",
  "gsutil",
  "gtk-update-icon-cache",
  "gtrash",
  "gulp",
  "gum",
  "gunzip",
  "gup",
  "gut",
  "gzip",
  "hadolint",
  "halt",
  "harlequin",
  "hatch",
  "hcloud",
  "head",
  "helix",
  "helm",
  "helm_ls",
  "helmfile",
  "helmsman",
  "hexchat",
  "hexdump",
  "hexyl",
  "hostid",
  "hostname",
  "hotbuild",
  "htop",
  "http",
  "httpie",
  "https",
  "hugetop",
  "hugo",
  "hurl",
  "hwinfo",
  "hx",
  "i3",
  "i3-scrot",
  "i3exit",
  "i3lock",
  "i3status",
  "i3status-rs",
  "id",
  "imv",
  "incus",
  "influx",
  "infracost",
  "inkscape",
  "inshellisense",
  "install",
  "ion",
  "ipinfo",
  "ipsw",
  "iredis",
  "istioctl",
  "jar",
  "jarsigner",
  "java",
  "javac",
  "javah",
  "jc",
  "jest",
  "jj",
  "join",
  "journalctl",
  "jq",
  "julia",
  "just",
  "k3d",
  "k3sup",
  "k6",
  "k9s",
  "kafkactl",
  "kak",
  "kak-lsp",
  "kamel",
  "kapp",
  "karabiner_cli",
  "karmadactl",
  "kconf",
  "kcptun_client",
  "kcptun_server",
  "keep-sorted",
  "keka",
  "keploy",
  "kill",
  "killall",
  "kind",
  "kitten",
  "kitty",
  "kk",
  "kmonad",
  "kn",
  "ko",
  "kompose",
  "kool",
  "kopia",
  "kops",
  "kor",
  "kosli",
  "kotlin",
  "kotlinc",
  "kraft",
  "ktlint",
  "kube-bench",
  "kube-linter",
  "kubeadm",
  "kubeaudit",
  "kubebuilder",
  "kubecfg",
  "kubecm",
  "kubectl",
  "kubectl-cnpg",
  "kubectl-krew",
  "kubectl-kuttl",
  "kubectl-oidc_login",
  "kubectl.lima",
  "kubefirst",
  "kubehound",
  "kubeone",
  "kubescape",
  "kubeseal",
  "kubeshark",
  "kubespy",
  "kubetail",
  "kubetui",
  "kubevpn",
  "kumactl",
  "kustomize",
  "kustomizer",
  "kwokctl",
  "kyma",
  "kyverno",
  "last",
  "lastb",
  "lastlog",
  "lazygit",
  "lefthook",
  "legit",
  "lf",
  "license-eye",
  "light",
  "lightdm",
  "lima-guestagent",
  "limactl",
  "link",
  "litecli",
  "litmusctl",
  "ln",
  "lnav",
  "lncrawl",
  "locale",
  "localectl",
  "localstack",
  "logname",
  "lolcrab",
  "ls",
  "lsb_release",
  "lsblk",
  "lsclocks",
  "lscpu",
  "lsfd",
  "lsirq",
  "lslocks",
  "lslogins",
  "lsmem",
  "lsns",
  "lsusb",
  "lua",
  "lux",
  "lzcat",
  "lzma",
  "macmon",
  "mactop",
  "magick",
  "make",
  "makepkg",
  "man",
  "mani",
  "marp",
  "mcap",
  "mcomix",
  "md5sum",
  "mdbook",
  "meld",
  "melt",
  "micro",
  "minikube",
  "mitmproxy",
  "mix",
  "mkcert",
  "mkdir",
  "mkfifo",
  "mkfs",
  "mknod",
  "mkswap",
  "mktemp",
  "mocha",
  "modinfo",
  "modprobe",
  "molecule",
  "mongocli",
  "more",
  "mosh",
  "mount",
  "mousepad",
  "mpm",
  "mpv",
  "msfvenom",
  "multi-gitter",
  "mv",
  "mvn",
  "mycli",
  "n-m3u8dl-re",
  "nali",
  "name-that-hash",
  "nano",
  "native2ascii",
  "nc",
  "ncdu",
  "nelm",
  "neomutt",
  "neon",
  "neonctl",
  "nerdctl",
  "nerdctl.colima",
  "nerdctl.lima",
  "netcat",
  "newman",
  "newrelic",
  "nfpm",
  "ng",
  "ngrok",
  "nice",
  "nilaway",
  "nix",
  "nix-build",
  "nix-channel",
  "nix-instantiate",
  "nix-shell",
  "nixos-rebuild",
  "njsscan",
  "nl",
  "nmcli",
  "node",
  "nodejsscan",
  "nohup",
  "nomad",
  "notation",
  "npm",
  "npm-check-updates",
  "npq",
  "npq-hero",
  "nproc",
  "ntfy",
  "nth",
  "ntpd",
  "nu",
  "nvim",
  "oc",
  "oci",
  "ocm",
  "od",
  "oh-my-posh",
  "ollama",
  "op",
  "op.exe",
  "opa",
  "openapi",
  "openscad",
  "ops",
  "optipng",
  "orb",
  "orbctl",
  "osascript",
  "packer",
  "pacman",
  "pacman-conf",
  "pacman-db-upgrade",
  "pacman-key",
  "pacman-mirrors",
  "palemoon",
  "pamac",
  "pandoc",
  "paru",
  "pass",
  "passwd",
  "paste",
  "patch",
  "pathchk",
  "pbcopy",
  "pbpaste",
  "pcmanfm",
  "pdfattach",
  "pdfdetach",
  "pdfseparate",
  "pdfsig",
  "pdftocairo",
  "pdftohtml",
  "pdftoppm",
  "pdfunite",
  "pgcli",
  "pgrep",
  "php",
  "phrase",
  "picard",
  "pidwait",
  "pigz",
  "ping",
  "pinky",
  "pio",
  "pip",
  "pipenv",
  "pipx",
  "pkg",
  "pkgsite",
  "pkgutil",
  "pkill",
  "pmap",
  "pngcheck",
  "pngquant",
  "pnpm",
  "pocketbase",
  "podman",
  "podman-remote",
  "podman-tui",
  "podman.lima",
  "policytool",
  "posting",
  "poweroff",
  "powertop",
  "pprof",
  "pr",
  "present",
  "prettybat",
  "prettyping",
  "printenv",
  "prism",
  "procs",
  "ps",
  "pscale",
  "ptx",
  "pulumi",
  "pwait",
  "pwd",
  "pwdx",
  "qbt",
  "qmk",
  "qpdf",
  "qrencode",
  "qutebrowser",
  "ranger",
  "ratify",
  "rclone",
  "rclone.exe",
  "readlink",
  "reboot",
  "redis-cli",
  "redocly",
  "regal",
  "regctl",
  "regula",
  "rekor-cli",
  "rename",
  "restic",
  "resume-cli",
  "retry",
  "reuse",
  "rg",
  "rg.exe=rg",
  "rich",
  "rifle",
  "rink",
  "ripsecrets",
  "rm",
  "rmdir",
  "rmmod",
  "roxctl",
  "rr",
  "rsync",
  "run0",
  "runme",
  "rust-analyzer",
  "rustc",
  "rustdoc",
  "rustup",
  "s5cmd",
  "sam",
  "sass",
  "saw",
  "scalar",
  "scooter",
  "scp",
  "script",
  "scriptlive",
  "scriptreplay",
  "scrot",
  "sd",
  "sdkmanager",
  "sdl2-config",
  "search-that-hash",
  "sed",
  "selene",
  "semver",
  "seq",
  "serie",
  "set-env",
  "sftp",
  "sget",
  "sha1sum",
  "sha256sum",
  "shadowenv",
  "shh",
  "showkey",
  "shred",
  "shutdown",
  "singularity",
  "skaffold",
  "skate",
  "skhd",
  "skopeo",
  "sleek",
  "sleep",
  "slides",
  "slsa-verifier",
  "soft",
  "sops",
  "sort",
  "spectral",
  "speedtest-cli",
  "split",
  "sqlc",
  "sqlfluff",
  "ssh",
  "ssh-agent",
  "ssh-copy-id",
  "ssh-keygen",
  "sshx",
  "st",
  "starship",
  "stat",
  "staticcheck",
  "stern",
  "strings",
  "stty",
  "stylua",
  "su",
  "sudo",
  "sudoedit",
  "sudoreplay",
  "sulogin",
  "sum",
  "supervisorctl",
  "supervisord",
  "svg-term",
  "svgcleaner",
  "sway",
  "swaybar",
  "swaybg",
  "swayidle",
  "swaylock",
  "swaymsg",
  "swaynag",
  "swctl",
  "syft",
  "sync",
  "sysctl",
  "systemctl",
  "systool",
  "tac",
  "tail",
  "taplo",
  "tar",
  "task",
  "tea",
  "tealdeer",
  "tee",
  "telnet",
  "templ",
  "temporal",
  "termux-apt-repo",
  "terraform",
  "terraform-ls",
  "terragrunt",
  "terramate",
  "tesseract",
  "tf-profile",
  "tic",
  "tig",
  "timer_analyser.d",
  "tinygo",
  "tldr",
  "tload",
  "tmate",
  "tmux",
  "tofu",
  "toit.lsp",
  "toit.pkg",
  "toolbox",
  "top",
  "tor-browser",
  "tor-gencert",
  "tor-print-ed-signing-cert",
  "tor-resolve",
  "torsocks",
  "touch",
  "tox",
  "tr",
  "traefik",
  "transmission-cli",
  "transmission-create",
  "transmission-daemon",
  "transmission-edit",
  "transmission-remote",
  "transmission-show",
  "tree",
  "treefmt",
  "trivy",
  "truncate",
  "ts",
  "tsc",
  "tsh",
  "tshark",
  "tsort",
  "tt",
  "tty",
  "ttyd",
  "turbo",
  "ufw",
  "umount",
  "uname",
  "unbrotli",
  "unexpand",
  "uniq",
  "unlink",
  "unlzma",
  "unpigz",
  "unset-env",
  "unxz",
  "unzip",
  "update-desktop-database",
  "update-mime-database",
  "upower",
  "uptime",
  "upx",
  "useradd",
  "userdel",
  "usermod",
  "users",
  "vagrant",
  "vault",
  "vdir",
  "velero",
  "vercel",
  "vhs",
  "vi",
  "viewnior",
  "vincent",
  "virtctl",
  "visudo",
  "viu",
  "vivid",
  "vlc",
  "vmrest",
  "volta",
  "vt",
  "vt.exe",
  "vultr",
  "vunnel",
  "w",
  "watch",
  "watchexec",
  "watchgnupg",
  "waypoint",
  "wc",
  "wezterm",
  "wget",
  "whalebrew",
  "whereis",
  "which",
  "who",
  "whoami",
  "wine",
  "wineboot",
  "winepath",
  "wineserver",
  "winetricks",
  "wire",
  "wireshark",
  "wishlist",
  "witness",
  "wl-mirror",
  "woeusb",
  "wormhole",
  "wrangler",
  "wslinfo",
  "wslpath",
  "xargs",
  "xbacklight",
  "xbps-digest",
  "xbps-fbulk",
  "xbps-fetch",
  "xclip",
  "xcode-select",
  "xdotool",
  "xeol",
  "xh",
  "xonsh",
  "xz",
  "xzcat",
  "yarn",
  "yarnpkg",
  "yay",
  "yes",
  "yj",
  "ykman",
  "youtube-dl",
  "yq",
  "yt-dlp",
  "ytt",
  "yubikey-agent",
  "zathura",
  "zcat",
  "zip",
  "zopfli",
  "zopflipng",
  "zoxide",
  "zx",
]

# These are here to simplify analisys of zsh completions & fish completions
# They include fish builtins, and some commands where site-functions should
# be available
# Creating dedicated empty compdef files for these can help avoid rebuilding
# the .zcompdump file when entering toolbox & distrobox containers
unreachable = [
  "_carapace_or_builtin",           # custom fish completion
  "abbr",
  "and",                            # fish builtin
  "argparse",                       # fish builtin
  "asp",
  "aura",                           # installed w/ aura, could be made external
  "bd",
  "begin",                          # fish builtin
  "block",                          # fish builtin
  "bootctl",                        # installed w/ systemd
  "busctl",                         # installed w/ systemd
  "cdh",                            # fish standard
  "commandline",                    # fish builtin
  "complete",                       # fish builtin
  "contains",                       # fish builtin
  "distrobox",
  "distrobox-assemble",
  "distrobox-create",
  "distrobox-enter",
  "distrobox-ephemeral",
  "distrobox-export",
  "distrobox-generate-entry",
  "distrobox-host-exec",
  "distrobox-init",
  "distrobox-list",
  "distrobox-rm",
  "distrobox-stop",
  "distrobox-upgrade",
  "ebuild",
  "eix",
  "eix-sync",
  "emaint",
  "emerge",
  "emit",                           # fish builtin
  "epkginfo",
  "equery",
  "eselect",
  "firejail",
  "firewall-cmd",                   # installed w/ firewalld
  "firewall-offline-cmd",           # installed w/ firewalld
  "fish_add_path",                  # fish standard
  "fish_config",                    # fish standard
  "fish_delta",                     # fish standard
  "fish_opt",                       # fish standard
  "funced",                         # fish standard
  "funcsave",                       # fish standard
  "hostnamectl",                    # installed w/ systemd
  "isatty",
  "kernel-install",                 # installed w/ systemd
  "lein",
  "llm",
  "loginctl",                       # installed w/ systemd
  "machinectl",                     # installed w/ systemd
  "math",                           # fish builtin
  "mkinitcpio",                     # installed w/ mkinitcpio
  "networkctl",                     # installed w/ systemd
  "nextd",                          # fish standard
  "not",                            # fish builtin
  "nvme",
  "oomctl",                         # installed w/ systemd
  "opam",
  "or",                             # fish builtin
  "ouch",
  "pacaur",
  "pacmatic",                       # installed w/ pacmatic
  "pactree",
  "path",                           # fish builtin
  "pkgfile",
  "powerpill",                      # installed w/ powerpill
  "prevd",                          # fish standard
  "psub",                           # fish standard
  "rbenv",
  "rc-service",                     # installed w/ openrc
  "rc-status",                      # installed w/ openrc
  "rc-update",                      # installed w/ openrc
  "resolvectl",                     # installed w/ systemd
  "run0",                           # installed w/ systemd
  "set_color",                      # fish builtin
  "sfdx",                           # salesforce cli, weird completion script
  "snap",
  "snapper",
  "string",                         # fish builtin
  "systemd-analyze",                # installed w/ systemd
  "systemd-ask-password",           # installed w/ systemd
  "systemd-cat",                    # installed w/ systemd
  "systemd-cgls",                   # installed w/ systemd
  "systemd-cgtop",                  # installed w/ systemd
  "systemd-delta",                  # installed w/ systemd
  "systemd-detect-virt",            # installed w/ systemd
  "systemd-inhibit",                # installed w/ systemd
  "systemd-machine-id-setup",       # installed w/ systemd
  "systemd-notify",                 # installed w/ systemd
  "systemd-nspawn",                 # installed w/ systemd
  "systemd-path",                   # installed w/ systemd
  "systemd-resolve",                # installed w/ systemd
  "systemd-run",                    # installed w/ systemd
  "systemd-tmpfiles",               # installed w/ systemd
  "systemd-tty-ask-password-agent", # installed w/ systemd
  "timedatectl",
  "tmuxinator",
  "toot",
  "typst",
  "udevadm",                        # installed w/ systemd
  "udisksctl",                      # installed w/ udisks2
  "varlinkctl",                     # installed w/ systemd
  "wpctl",                          # installed w/ wireplumber
  "xbps-alternatives",
  "xbps-checkvers",
  "xbps-create",
  "xbps-dgraph",
  "xbps-install",
  "xbps-pkgdb",
  "xbps-query",
  "xbps-reconfigure",
  "xbps-remove",
  "xbps-rindex",
  "xbps-uchroot",
  "xbps-uhelper",
  "yadm",
  "yaourt",
]
