[settings.lima.tmpfiles]
# tombi: format.rules.array-values-order = "ascending"
shared = [
  ".config/bat",
  ".config/bottom",
  ".config/carapace/bridge/bash",
  ".config/carapace/bridge/fish",
  ".config/carapace/bridge/powershell",
  ".config/carapace/overlays",
  ".config/carapace/specs",
  ".config/carapace/styles.json",
  ".config/carapace/variables",
  ".config/eza",
  ".config/fastfetch",
  ".config/fd",
  ".config/fish/completions",
  ".config/glow",
  ".config/powershell",
  ".config/rainbow",
  ".config/readline",
  ".config/starship.toml",
  ".config/vivid",
  ".config/zsh/functions",
  ".config/zsh/plugins",
  ".config/zsh/vendor",
]
