# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
title: App Settings
type: object
properties:
  bat: { $ref: ./settings/bat.json }
  chezmoi: { $ref: ./settings/chezmoi.yaml }
  homebrew: { $ref: ./settings/homebrew.yaml }
  launchd: { $ref: ./settings/launchd.yaml }
  kitty: { $ref: ./settings/kitty.yaml }
  shell: { $ref: ./settings/shell.yaml }
  systemd: { $ref: ./settings/systemd.yaml }
